version: "3.8"

services:
  composer:
      image: composer:1
      entrypoint: composer
      command: install --ignore-platform-reqs
      volumes:
          - ./symfony-example:/app

  nginx:
      image: nginx:latest
      depends_on: ['php']
      ports:
          - "8080:80"
      volumes:
          - code:/var/www
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
      networks:
        - backend

  php:
      build:
        context: '.'
      volumes:
          - code:/var/www
      networks:
        - backend

networks:
  backend:

volumes:
  code: